# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.luks.devices."luks-fb81a4a7-0dbb-4528-86ae-b47d6f7f0ec6".device = "/dev/disk/by-uuid/fb81a4a7-0dbb-4528-86ae-b47d6f7f0ec6";
  boot.kernelParams = [ "amdgpu.dcdebugmask=0x10" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8f9a960e-f812-45c3-9bfc-a6434384fa47";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8f9a960e-f812-45c3-9bfc-a6434384fa47".device = "/dev/disk/by-uuid/8f9a960e-f812-45c3-9bfc-a6434384fa47";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8B9A-F4DD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fb81a4a7-0dbb-4528-86ae-b47d6f7f0ec6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
